version: '3.8'

services:
  backend:
    build:
      context: ./backend-php
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=challenge_db
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./backend-php:/var/www
    depends_on:
      - mysql
      - redis

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=challenge_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: